### ISSUE TITLE
Please enable discussions 

### ISSUE THREAD

**Issue by asdf8dfafjk** [Simhyeon/r4d#4]
So that the community can discuss if they need help. Great and modern btw, m4 was unweidly since it prohibits `$` and doesn't even have a foreach!

**Comment by Simhyeon** [comment]
Oops my bad. I have been so busy doing my other businesses and I just enabled discussions. Although I have to tell you that now I'm not related to tech industry anymore. I am going to restart maintaining my projects but not until my issue is resolved. 

Anyway thank you for the interest and have fun using macros!

**Comment by asdf8dfafjk** [comment]
Which hedge fund got you!? Great project, thank you so much.
